/**
 * Hybrid short-term + semantic memory module.
 *
 * Combines two storage layers:
 * 1. **Local ring buffer** — holds the `MAX_ENTRIES` most recent
 *    strings for ultra-low-latency continuity.
 * 2. **Qdrant vector store** — stores embeddings generated by
 *    Ollama for cross-task semantic recall.
 *
 * When Qdrant is unavailable the system silently falls back to the
 * ring buffer so the agent keeps working without errors.
 *
 * @module memory/memory
 */

import { randomUUID } from 'node:crypto';
import { QdrantClient } from '@qdrant/js-client-rest';
import { logger } from '../logger/logger';
import { getEmbedding } from '../llm/embeddings';
import type { IMemoryEntry } from './types';

/* ── Configuration from environment ──────────────────────────────────── */

/** Maximum entries kept in the in-process ring buffer. */
const MAX_ENTRIES = 20;

/** Default cap on the number of memory strings returned by `getMemory`. */
const DEFAULT_RETURN_COUNT = 10;

/** URL of the Qdrant vector database REST API. */
const QDRANT_URL = process.env.QDRANT_URL ?? 'http://localhost:6333';

/** Qdrant collection name where memory vectors are stored. */
const QDRANT_COLLECTION = process.env.QDRANT_COLLECTION ?? 'agent_memory';

/* ── In-process state ────────────────────────────────────────────────── */

/** Ring buffer of the most recent memory strings (FIFO). */
const recentMemory: string[] = [];

/** Qdrant REST client — lazy-connected on first use. */
const qdrant = new QdrantClient({ url: QDRANT_URL });

/** Flipped to `false` when Qdrant is unreachable, to avoid repeated errors. */
let qdrantEnabled = true;

/** Cached vector dimension size from the first embedding call. */
let vectorSize: number | null = null;

/** Singleton promise to prevent concurrent collection creation races. */
let ensureCollectionPromise: Promise<void> | null = null;

/* ── Internal helpers ────────────────────────────────────────────────── */

/**
 * Append a string to the ring buffer, evicting the oldest entry
 * when the buffer exceeds `MAX_ENTRIES`.
 *
 * @param entry - Plain text memory string.
 */
function addToRecentMemory(entry: string): void {
    recentMemory.push(entry);
    if (recentMemory.length > MAX_ENTRIES) {
        recentMemory.shift();
    }
}

/**
 * Log helper for the "memory added, local only" path.
 *
 * @param startedAt - Timestamp (ms) when the operation began.
 */
function logMemoryAddedLocalOnly(startedAt: number): void {
    logger.info('memory_added_local_only', {
        component: 'memory',
        recentCount: recentMemory.length,
        durationMs: Date.now() - startedAt
    });
}

/**
 * Log helper for the "memory cleared, local only" path.
 *
 * @param startedAt - Timestamp (ms) when the operation began.
 */
function logMemoryClearedRecentOnly(startedAt: number): void {
    logger.info('memory_cleared_recent_only', {
        component: 'memory',
        durationMs: Date.now() - startedAt
    });
}

/**
 * Ensure the Qdrant collection exists, creating it if necessary.
 *
 * Uses a singleton promise to prevent race conditions when multiple
 * concurrent calls try to create the collection at the same time.
 *
 * @param size - Required vector dimension size for the collection.
 */
async function ensureCollection(size: number): Promise<void> {
    if (ensureCollectionPromise) {
        return ensureCollectionPromise;
    }

    ensureCollectionPromise = (
        qdrant.getCollection(QDRANT_COLLECTION).catch(() =>
            qdrant.createCollection(QDRANT_COLLECTION, {
                vectors: { size, distance: 'Cosine' }
            })
        ) as Promise<unknown>
    ).then(() => undefined);

    await ensureCollectionPromise.finally(() => {
        ensureCollectionPromise = null;
    });
}

/* ── Public API ──────────────────────────────────────────────────────── */

/**
 * Append a plain-text entry to both the local ring buffer and Qdrant.
 *
 * When Qdrant is unavailable the entry is stored in the ring buffer
 * only.  Qdrant is permanently disabled for this process once the
 * first error is encountered (to avoid repeated slow failures).
 *
 * @param entry - The text to persist as a memory entry.
 */
export async function addMemory(entry: string): Promise<void> {
    const startedAt = Date.now();
    addToRecentMemory(entry);

    if (!qdrantEnabled) {
        logMemoryAddedLocalOnly(startedAt);
        return;
    }

    await getEmbedding(entry)
        .then((vector) => {
            vectorSize = vector.length;
            return ensureCollection(vector.length)
                .then(() =>
                    qdrant.upsert(QDRANT_COLLECTION, {
                        wait: true,
                        points: [
                            {
                                id: randomUUID(),
                                vector,
                                payload: { text: entry, createdAt: new Date().toISOString() }
                            }
                        ]
                    })
                )
                .then(() => {
                    logger.info('memory_added', {
                        component: 'memory',
                        recentCount: recentMemory.length,
                        vectorSize,
                        durationMs: Date.now() - startedAt
                    });
                });
        })
        .catch((error: unknown) => {
            qdrantEnabled = false;
            logger.warn('memory_qdrant_disabled', {
                component: 'memory',
                error: String(error),
                message: 'Falling back to in-memory only'
            });
            logMemoryAddedLocalOnly(startedAt);
        });
}

/**
 * Retrieve a combined list of recent + semantically relevant memories.
 *
 * When Qdrant is available the results are a de-duplicated merge of
 * the most recent ring-buffer entries and the top semantic matches
 * from the vector store.  When Qdrant is unavailable only the ring
 * buffer entries are returned.
 *
 * @param query - Natural-language query used for semantic retrieval (optional).
 * @param n     - Maximum number of memory strings to return (default: 10).
 * @returns An array of memory strings (oldest → newest).
 */
export async function getMemory(query = '', n = DEFAULT_RETURN_COUNT): Promise<string[]> {
    const startedAt = Date.now();
    const cappedN = Math.max(1, n);
    const recent = recentMemory.slice(-cappedN);

    if (!qdrantEnabled || query.trim() === '') {
        logger.info('memory_read_recent_only', {
            component: 'memory',
            queryLength: query.length,
            returnedCount: recent.length,
            qdrantEnabled,
            durationMs: Date.now() - startedAt
        });
        return recent;
    }

    return getEmbedding(query)
        .then((queryVector) =>
            ensureCollection(queryVector.length).then(() =>
                qdrant.search(QDRANT_COLLECTION, {
                    vector: queryVector,
                    limit: cappedN,
                    with_payload: true
                })
            )
        )
        .then((results) => {
            /* Extract text payloads from Qdrant search results. */
            const semantic = results
                .map((point) => {
                    const payload = point.payload as { text?: unknown } | null | undefined;
                    return typeof payload?.text === 'string' ? payload.text : null;
                })
                .filter((value): value is string => value !== null);

            /* Merge recent + semantic, de-duplicating by exact text match. */
            const merged: string[] = [...recent];
            const seen = new Set(merged);
            for (const item of semantic) {
                if (!seen.has(item)) {
                    merged.push(item);
                    seen.add(item);
                }
            }
            const output = merged.slice(0, cappedN);
            logger.info('memory_read_hybrid', {
                component: 'memory',
                queryLength: query.length,
                recentCount: recent.length,
                semanticCount: semantic.length,
                returnedCount: output.length,
                durationMs: Date.now() - startedAt
            });
            return output;
        })
        .catch((error: unknown) => {
            logger.warn('memory_qdrant_search_failed', {
                component: 'memory',
                error: String(error),
                queryLength: query.length,
                returnedCount: recent.length,
                durationMs: Date.now() - startedAt
            });
            return recent;
        });
}

/**
 * Wipe all memory — both the local ring buffer and the Qdrant collection.
 *
 * If Qdrant is unavailable only the ring buffer is cleared.
 */
export async function clearMemory(): Promise<void> {
    const startedAt = Date.now();
    recentMemory.length = 0;

    if (!qdrantEnabled) {
        logMemoryClearedRecentOnly(startedAt);
        return;
    }

    await qdrant
        .deleteCollection(QDRANT_COLLECTION)
        .then(() => {
            vectorSize = null;
            logger.info('memory_cleared', {
                component: 'memory',
                durationMs: Date.now() - startedAt
            });
        })
        .catch((error: unknown) => {
            logger.warn('memory_clear_failed', {
                component: 'memory',
                error: String(error),
                durationMs: Date.now() - startedAt
            });
            logMemoryClearedRecentOnly(startedAt);
        });
}

/**
 * Add a structured `MemoryEntry` to memory.
 *
 * Follows Mastra's pattern of storing typed entries with role and
 * metadata.  The `content` field is used as the text stored in
 * Qdrant; all fields are persisted as Qdrant payload so you can
 * filter by role / metadata later.
 *
 * Falls back gracefully to the plain `addMemory` path if any extra
 * fields cause issues.
 *
 * @param entry - Structured memory entry (role, content, metadata, etc.)
 *                without `id` and `timestamp` which are auto-generated.
 */
export async function addStructuredMemory(
    entry: Omit<IMemoryEntry, 'id' | 'timestamp'>
): Promise<void> {
    const startedAt = Date.now();
    const id = randomUUID();
    const timestamp = new Date();
    const fullEntry: IMemoryEntry = { id, timestamp, ...entry };

    addToRecentMemory(fullEntry.content);

    if (!qdrantEnabled) {
        logMemoryAddedLocalOnly(startedAt);
        return;
    }

    await getEmbedding(fullEntry.content)
        .then((vector) => {
            vectorSize = vector.length;
            return ensureCollection(vector.length)
                .then(() =>
                    qdrant.upsert(QDRANT_COLLECTION, {
                        wait: true,
                        points: [
                            {
                                id,
                                vector,
                                payload: {
                                    text: fullEntry.content,
                                    role: fullEntry.role,
                                    createdAt: timestamp.toISOString(),
                                    ...(fullEntry.metadata ?? {})
                                }
                            }
                        ]
                    })
                )
                .then(() => {
                    logger.info('memory_structured_added', {
                        component: 'memory',
                        id,
                        role: fullEntry.role,
                        recentCount: recentMemory.length,
                        vectorSize,
                        durationMs: Date.now() - startedAt
                    });
                });
        })
        .catch((error: unknown) => {
            qdrantEnabled = false;
            logger.warn('memory_qdrant_disabled', {
                component: 'memory',
                error: String(error),
                message: 'Falling back to in-memory only'
            });
            logMemoryAddedLocalOnly(startedAt);
        });
}

/**
 * Trim a list of memory entries to fit within a character budget.
 *
 * Adopting Mastra's context-window optimisation pattern — instead of
 * blindly sending all memory to the LLM, keep only what fits in
 * `maxChars` while preferring the *most recent* entries (last items
 * in the array).
 *
 * @param entries  - Memory strings ordered oldest → newest.
 * @param maxChars - Maximum total character budget (default: 8 000).
 * @returns A subset of entries that fits within the budget.
 */
export function optimizeContextWindow(entries: string[], maxChars = 8_000): string[] {
    if (entries.length === 0) return [];

    const result: string[] = [];
    let total = 0;

    /* Walk from newest to oldest, filling the budget. */
    for (let i = entries.length - 1; i >= 0; i--) {
        const entry = entries[i];
        if (total + entry.length > maxChars) break;
        result.unshift(entry);
        total += entry.length;
    }

    logger.info('memory_context_optimized', {
        component: 'memory',
        inputCount: entries.length,
        outputCount: result.length,
        totalChars: total,
        maxChars
    });

    return result;
}
