/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  HealthResponse,
  RunRequest,
  RunResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    HealthResponseFromJSON,
    HealthResponseToJSON,
    RunRequestFromJSON,
    RunRequestToJSON,
    RunResponseFromJSON,
    RunResponseToJSON,
} from '../models/index';

export interface PostRunRequest {
    runRequest: RunRequest;
}

export interface PostRunStreamRequest {
    runRequest: RunRequest;
}

/**
 * 
 */
export class CoreApi extends runtime.BaseAPI {

    /**
     * Returns `{ status: ok }` without calling any LLM. Use for liveness probes.
     * Health check
     */
    async getHealthRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HealthResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/health`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HealthResponseFromJSON(jsonValue));
    }

    /**
     * Returns `{ status: ok }` without calling any LLM. Use for liveness probes.
     * Health check
     */
    async getHealth(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HealthResponse> {
        const response = await this.getHealthRaw(initOverrides);
        return await response.value();
    }

    /**
     * Triggers the full agentic loop: model routing → tool selection → execution → repeat (up to `MAX_STEPS`, default 5). Returns the agent\'s final answer as a string.  This is the right endpoint whenever no specialised endpoint covers the use case. 
     * Submit a task to the agent reasoning loop
     */
    async postRunRaw(requestParameters: PostRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RunResponse>> {
        if (requestParameters['runRequest'] == null) {
            throw new runtime.RequiredError(
                'runRequest',
                'Required parameter "runRequest" was null or undefined when calling postRun().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/run`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RunRequestToJSON(requestParameters['runRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RunResponseFromJSON(jsonValue));
    }

    /**
     * Triggers the full agentic loop: model routing → tool selection → execution → repeat (up to `MAX_STEPS`, default 5). Returns the agent\'s final answer as a string.  This is the right endpoint whenever no specialised endpoint covers the use case. 
     * Submit a task to the agent reasoning loop
     */
    async postRun(requestParameters: PostRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RunResponse> {
        const response = await this.postRunRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Same as `POST /run` but streams agent lifecycle events in real time as Server-Sent Events (SSE).  The connection stays open until the agent completes (on `done`, `error`, or `max_steps` event). The original `POST /run` endpoint is completely unchanged.  **SSE event types**: - `step` — emitted after each LLM response: `{ step, action, thought }` - `tool` — emitted after each tool execution: `{ tool, result? }` or `{ tool, error }` - `route` — emitted when a model profile is selected: `{ profile, model, reason }` - `done` — final answer ready: `{ result, meta? }` - `error` — agent threw: `{ error }` - `max_steps` — loop exhausted: `{ task, summary }` 
     * Submit a task and receive Server-Sent Events
     */
    async postRunStreamRaw(requestParameters: PostRunStreamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['runRequest'] == null) {
            throw new runtime.RequiredError(
                'runRequest',
                'Required parameter "runRequest" was null or undefined when calling postRunStream().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/run/stream`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RunRequestToJSON(requestParameters['runRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Same as `POST /run` but streams agent lifecycle events in real time as Server-Sent Events (SSE).  The connection stays open until the agent completes (on `done`, `error`, or `max_steps` event). The original `POST /run` endpoint is completely unchanged.  **SSE event types**: - `step` — emitted after each LLM response: `{ step, action, thought }` - `tool` — emitted after each tool execution: `{ tool, result? }` or `{ tool, error }` - `route` — emitted when a model profile is selected: `{ profile, model, reason }` - `done` — final answer ready: `{ result, meta? }` - `error` — agent threw: `{ error }` - `max_steps` — loop exhausted: `{ task, summary }` 
     * Submit a task and receive Server-Sent Events
     */
    async postRunStream(requestParameters: PostRunStreamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.postRunStreamRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
