/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AutocompleteRequest,
  AutocompleteResponse,
  ErrorResponse,
  LintConventionsRequest,
  LintResponse,
  PageReviewRequest,
  PageReviewResponse,
} from '../models/index';
import {
    AutocompleteRequestFromJSON,
    AutocompleteRequestToJSON,
    AutocompleteResponseFromJSON,
    AutocompleteResponseToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    LintConventionsRequestFromJSON,
    LintConventionsRequestToJSON,
    LintResponseFromJSON,
    LintResponseToJSON,
    PageReviewRequestFromJSON,
    PageReviewRequestToJSON,
    PageReviewResponseFromJSON,
    PageReviewResponseToJSON,
} from '../models/index';

export interface PostAutocompleteRequest {
    autocompleteRequest: AutocompleteRequest;
}

export interface PostLintConventionsRequest {
    lintConventionsRequest: LintConventionsRequest;
}

export interface PostPageReviewRequest {
    pageReviewRequest: PageReviewRequest;
}

/**
 * 
 */
export class IdeApi extends runtime.BaseAPI {

    /**
     * Single LLM call (no agent loop). Returns one or more code completion suggestions for the given cursor position. Uses `TOOL_IDE_MODEL` (default `starcoder2`).  Intended for IDE integration. Responses are cached for identical prefix/suffix pairs. 
     * Cursor-time code completion
     */
    async postAutocompleteRaw(requestParameters: PostAutocompleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AutocompleteResponse>> {
        if (requestParameters['autocompleteRequest'] == null) {
            throw new runtime.RequiredError(
                'autocompleteRequest',
                'Required parameter "autocompleteRequest" was null or undefined when calling postAutocomplete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/autocomplete`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AutocompleteRequestToJSON(requestParameters['autocompleteRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AutocompleteResponseFromJSON(jsonValue));
    }

    /**
     * Single LLM call (no agent loop). Returns one or more code completion suggestions for the given cursor position. Uses `TOOL_IDE_MODEL` (default `starcoder2`).  Intended for IDE integration. Responses are cached for identical prefix/suffix pairs. 
     * Cursor-time code completion
     */
    async postAutocomplete(requestParameters: PostAutocompleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AutocompleteResponse> {
        const response = await this.postAutocompleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Runs deterministic TypeScript/style checks and optionally enriches findings with LLM explanations. Returns a structured list of findings with severity, rule name, line numbers, and suggested fixes. 
     * Deterministic lint + LLM convention findings
     */
    async postLintConventionsRaw(requestParameters: PostLintConventionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LintResponse>> {
        if (requestParameters['lintConventionsRequest'] == null) {
            throw new runtime.RequiredError(
                'lintConventionsRequest',
                'Required parameter "lintConventionsRequest" was null or undefined when calling postLintConventions().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/lint-conventions`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LintConventionsRequestToJSON(requestParameters['lintConventionsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LintResponseFromJSON(jsonValue));
    }

    /**
     * Runs deterministic TypeScript/style checks and optionally enriches findings with LLM explanations. Returns a structured list of findings with severity, rule name, line numbers, and suggested fixes. 
     * Deterministic lint + LLM convention findings
     */
    async postLintConventions(requestParameters: PostLintConventionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LintResponse> {
        const response = await this.postLintConventionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Single LLM call that analyses a full source file and returns categorised review suggestions (correctness, maintainability, performance, security). 
     * Whole-file categorised engineering review
     */
    async postPageReviewRaw(requestParameters: PostPageReviewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PageReviewResponse>> {
        if (requestParameters['pageReviewRequest'] == null) {
            throw new runtime.RequiredError(
                'pageReviewRequest',
                'Required parameter "pageReviewRequest" was null or undefined when calling postPageReview().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/page-review`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PageReviewRequestToJSON(requestParameters['pageReviewRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PageReviewResponseFromJSON(jsonValue));
    }

    /**
     * Single LLM call that analyses a full source file and returns categorised review suggestions (correctness, maintainability, performance, security). 
     * Whole-file categorised engineering review
     */
    async postPageReview(requestParameters: PostPageReviewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PageReviewResponse> {
        const response = await this.postPageReviewRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
