/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetHelp200Response,
  GetInfoModels200Response,
  GetInfoModels502Response,
  GetInfoModes200Response,
} from '../models/index';
import {
    GetHelp200ResponseFromJSON,
    GetHelp200ResponseToJSON,
    GetInfoModels200ResponseFromJSON,
    GetInfoModels200ResponseToJSON,
    GetInfoModels502ResponseFromJSON,
    GetInfoModels502ResponseToJSON,
    GetInfoModes200ResponseFromJSON,
    GetInfoModes200ResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class InfoApi extends runtime.BaseAPI {

    /**
     * Returns a structured JSON overview of every endpoint exposed by the Manna API — equivalent to `--help` on a CLI tool. Includes HTTP method, path, summary, and parameter list for each endpoint. No LLM call. 
     * Quick reference of all available REST API endpoints
     */
    async getHelpRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetHelp200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/help`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetHelp200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns a structured JSON overview of every endpoint exposed by the Manna API — equivalent to `--help` on a CLI tool. Includes HTTP method, path, summary, and parameter list for each endpoint. No LLM call. 
     * Quick reference of all available REST API endpoints
     */
    async getHelp(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetHelp200Response> {
        const response = await this.getHelpRaw(initOverrides);
        return await response.value();
    }

    /**
     * Proxies Ollama\'s `GET /api/tags` endpoint and returns the list of locally available models with size, digest, and detail metadata. Returns 502 if Ollama is unreachable. 
     * List models currently available in the connected Ollama instance
     */
    async getInfoModelsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetInfoModels200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/info/models`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetInfoModels200ResponseFromJSON(jsonValue));
    }

    /**
     * Proxies Ollama\'s `GET /api/tags` endpoint and returns the list of locally available models with size, digest, and detail metadata. Returns 502 if Ollama is unreachable. 
     * List models currently available in the connected Ollama instance
     */
    async getInfoModels(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetInfoModels200Response> {
        const response = await this.getInfoModelsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Returns all recognised agent routing profiles, the Ollama model currently configured for each, the controlling environment variable, and a human-readable description. No LLM call is made. 
     * List available Manna agent routing profiles (modes)
     */
    async getInfoModesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetInfoModes200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/info/modes`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetInfoModes200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns all recognised agent routing profiles, the Ollama model currently configured for each, the controlling environment variable, and a human-readable description. No LLM call is made. 
     * List available Manna agent routing profiles (modes)
     */
    async getInfoModes(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetInfoModes200Response> {
        const response = await this.getInfoModesRaw(initOverrides);
        return await response.value();
    }

}
