/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ArticleExport,
  ErrorResponse,
  ImportRequest,
  ImportResult,
  LibraryInfo,
  RankedArticle,
  SearchRequest,
} from '../models/index';
import {
    ArticleExportFromJSON,
    ArticleExportToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ImportRequestFromJSON,
    ImportRequestToJSON,
    ImportResultFromJSON,
    ImportResultToJSON,
    LibraryInfoFromJSON,
    LibraryInfoToJSON,
    RankedArticleFromJSON,
    RankedArticleToJSON,
    SearchRequestFromJSON,
    SearchRequestToJSON,
} from '../models/index';

export interface ExportLibraryRequest {
    libraryId: string;
}

export interface ImportLibraryRequest {
    libraryId: string;
    importRequest: ImportRequest;
}

export interface SearchLibraryRequest {
    libraryId: string;
    searchRequest: SearchRequest;
}

/**
 * 
 */
export class LibraryApi extends runtime.BaseAPI {

    /**
     * Returns the full article metadata index for the library as a JSON array. Intended for human review, manual editing, or backup.  The exported JSON can be inspected to verify ingestion quality (summaries, topic tags, page numbers) and re-imported after manual corrections.  Embedding vectors are excluded from the export to keep the response size manageable. Re-embedding is required if the index is rebuilt from scratch. 
     * Export all article metadata as JSON
     */
    async exportLibraryRaw(requestParameters: ExportLibraryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ArticleExport>>> {
        if (requestParameters['libraryId'] == null) {
            throw new runtime.RequiredError(
                'libraryId',
                'Required parameter "libraryId" was null or undefined when calling exportLibrary().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/library/{libraryId}/export`.replace(`{${"libraryId"}}`, encodeURIComponent(String(requestParameters['libraryId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ArticleExportFromJSON));
    }

    /**
     * Returns the full article metadata index for the library as a JSON array. Intended for human review, manual editing, or backup.  The exported JSON can be inspected to verify ingestion quality (summaries, topic tags, page numbers) and re-imported after manual corrections.  Embedding vectors are excluded from the export to keep the response size manageable. Re-embedding is required if the index is rebuilt from scratch. 
     * Export all article metadata as JSON
     */
    async exportLibrary(requestParameters: ExportLibraryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ArticleExport>> {
        const response = await this.exportLibraryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Ingests one or more PDF files (or an entire folder) into the specified library. Runs the two-pass pipeline:  1. **Pass 1 — Structure discovery**: the LLM reads the table-of-contents pages    of each PDF to extract article titles and page ranges. 2. **Pass 2 — Content extraction**: for each article, the LLM summarises the    text and generates topic tags; the summary is embedded and stored in Qdrant.  Accepts **either** `pdfs` (array of specific files) **or** `folder` (directory path). If both are provided, `pdfs` takes precedence.  This is a long-running operation. For large archives (hundreds of PDFs), it may take minutes to hours. The endpoint returns only after all PDFs are processed. Failed PDFs are reported in the `errors` array without aborting the batch.  See the Library Ingestion documentation for full architecture details. 
     * Import PDFs into a library using the two-pass ingestion pipeline
     */
    async importLibraryRaw(requestParameters: ImportLibraryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ImportResult>> {
        if (requestParameters['libraryId'] == null) {
            throw new runtime.RequiredError(
                'libraryId',
                'Required parameter "libraryId" was null or undefined when calling importLibrary().'
            );
        }

        if (requestParameters['importRequest'] == null) {
            throw new runtime.RequiredError(
                'importRequest',
                'Required parameter "importRequest" was null or undefined when calling importLibrary().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/library/{libraryId}/import`.replace(`{${"libraryId"}}`, encodeURIComponent(String(requestParameters['libraryId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ImportRequestToJSON(requestParameters['importRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ImportResultFromJSON(jsonValue));
    }

    /**
     * Ingests one or more PDF files (or an entire folder) into the specified library. Runs the two-pass pipeline:  1. **Pass 1 — Structure discovery**: the LLM reads the table-of-contents pages    of each PDF to extract article titles and page ranges. 2. **Pass 2 — Content extraction**: for each article, the LLM summarises the    text and generates topic tags; the summary is embedded and stored in Qdrant.  Accepts **either** `pdfs` (array of specific files) **or** `folder` (directory path). If both are provided, `pdfs` takes precedence.  This is a long-running operation. For large archives (hundreds of PDFs), it may take minutes to hours. The endpoint returns only after all PDFs are processed. Failed PDFs are reported in the `errors` array without aborting the batch.  See the Library Ingestion documentation for full architecture details. 
     * Import PDFs into a library using the two-pass ingestion pipeline
     */
    async importLibrary(requestParameters: ImportLibraryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ImportResult> {
        const response = await this.importLibraryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns all registered libraries with their configuration metadata and ingestion status (article count, last import timestamp). 
     * List all libraries
     */
    async listLibrariesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<LibraryInfo>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/library`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(LibraryInfoFromJSON));
    }

    /**
     * Returns all registered libraries with their configuration metadata and ingestion status (article count, last import timestamp). 
     * List all libraries
     */
    async listLibraries(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<LibraryInfo>> {
        const response = await this.listLibrariesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Embeds the query using `OLLAMA_EMBED_MODEL` (default `nomic-embed-text`) and performs ANN cosine similarity search over the library\'s article embedding index in Qdrant.  Returns a ranked list of articles with metadata, PDF path, and similarity score. The caller can use the returned `pdfPath` and `startPage` to open the exact article in the PDF viewer.  Optional `filters` allow narrowing results by publication year and/or month. Optional `topK` controls how many articles are returned (default: 5).  See the Library Ingestion documentation for full architecture details. 
     * Semantic article search within a specific library
     */
    async searchLibraryRaw(requestParameters: SearchLibraryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<RankedArticle>>> {
        if (requestParameters['libraryId'] == null) {
            throw new runtime.RequiredError(
                'libraryId',
                'Required parameter "libraryId" was null or undefined when calling searchLibrary().'
            );
        }

        if (requestParameters['searchRequest'] == null) {
            throw new runtime.RequiredError(
                'searchRequest',
                'Required parameter "searchRequest" was null or undefined when calling searchLibrary().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/library/{libraryId}/search`.replace(`{${"libraryId"}}`, encodeURIComponent(String(requestParameters['libraryId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SearchRequestToJSON(requestParameters['searchRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(RankedArticleFromJSON));
    }

    /**
     * Embeds the query using `OLLAMA_EMBED_MODEL` (default `nomic-embed-text`) and performs ANN cosine similarity search over the library\'s article embedding index in Qdrant.  Returns a ranked list of articles with metadata, PDF path, and similarity score. The caller can use the returned `pdfPath` and `startPage` to open the exact article in the PDF viewer.  Optional `filters` allow narrowing results by publication year and/or month. Optional `topK` controls how many articles are returned (default: 5).  See the Library Ingestion documentation for full architecture details. 
     * Semantic article search within a specific library
     */
    async searchLibrary(requestParameters: SearchLibraryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<RankedArticle>> {
        const response = await this.searchLibraryRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
