/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  SwarmRequest,
  SwarmResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    SwarmRequestFromJSON,
    SwarmRequestToJSON,
    SwarmResponseFromJSON,
    SwarmResponseToJSON,
} from '../models/index';

export interface PostRunSwarmRequest {
    swarmRequest: SwarmRequest;
}

export interface PostRunSwarmStreamRequest {
    swarmRequest: SwarmRequest;
}

/**
 * 
 */
export class SwarmApi extends runtime.BaseAPI {

    /**
     * Decomposes the task into subtasks using an LLM, executes each subtask through a specialised agent (respecting dependency ordering), and synthesises a final answer from all subtask results.  Use this instead of `POST /run` when the task is complex enough to benefit from divide-and-conquer (e.g. \"build X, write tests, and document it\"). 
     * Run a multi-agent swarm to solve a complex task
     */
    async postRunSwarmRaw(requestParameters: PostRunSwarmRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SwarmResponse>> {
        if (requestParameters['swarmRequest'] == null) {
            throw new runtime.RequiredError(
                'swarmRequest',
                'Required parameter "swarmRequest" was null or undefined when calling postRunSwarm().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/run/swarm`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SwarmRequestToJSON(requestParameters['swarmRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SwarmResponseFromJSON(jsonValue));
    }

    /**
     * Decomposes the task into subtasks using an LLM, executes each subtask through a specialised agent (respecting dependency ordering), and synthesises a final answer from all subtask results.  Use this instead of `POST /run` when the task is complex enough to benefit from divide-and-conquer (e.g. \"build X, write tests, and document it\"). 
     * Run a multi-agent swarm to solve a complex task
     */
    async postRunSwarm(requestParameters: PostRunSwarmRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SwarmResponse> {
        const response = await this.postRunSwarmRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Same as `POST /run/swarm`, but streams agent lifecycle events as Server-Sent Events. The connection stays open until the swarm completes.  SSE event types: `decomposed`, `subtask_start`, `subtask_done`, `subtask_error`, `step`, `tool`, `route`, `done`, `error`. The terminal `done` event includes `{ answer, totalDurationMs, subtaskCount, meta? }`. 
     * Run a multi-agent swarm with SSE streaming
     */
    async postRunSwarmStreamRaw(requestParameters: PostRunSwarmStreamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['swarmRequest'] == null) {
            throw new runtime.RequiredError(
                'swarmRequest',
                'Required parameter "swarmRequest" was null or undefined when calling postRunSwarmStream().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/run/swarm/stream`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SwarmRequestToJSON(requestParameters['swarmRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Same as `POST /run/swarm`, but streams agent lifecycle events as Server-Sent Events. The connection stays open until the swarm completes.  SSE event types: `decomposed`, `subtask_start`, `subtask_done`, `subtask_error`, `step`, `tool`, `route`, `done`, `error`. The terminal `done` event includes `{ answer, totalDurationMs, subtaskCount, meta? }`. 
     * Run a multi-agent swarm with SSE streaming
     */
    async postRunSwarmStream(requestParameters: PostRunSwarmStreamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.postRunSwarmStreamRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
