/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  ImageProcessorResponse,
  UploadImageClassify200Response,
  UploadReadPdf200Response,
  UploadSpeechToText200Response,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ImageProcessorResponseFromJSON,
    ImageProcessorResponseToJSON,
    UploadImageClassify200ResponseFromJSON,
    UploadImageClassify200ResponseToJSON,
    UploadReadPdf200ResponseFromJSON,
    UploadReadPdf200ResponseToJSON,
    UploadSpeechToText200ResponseFromJSON,
    UploadSpeechToText200ResponseToJSON,
} from '../models/index';

export interface UploadImageClassifyRequest {
    file: Blob;
    prompt?: string;
    model?: string;
}

export interface UploadImageColorizeRequest {
    file: Blob;
    prompt?: string;
    negativePrompt?: string;
}

export interface UploadImageSketchRequest {
    file: Blob;
    prompt?: string;
    negativePrompt?: string;
}

export interface UploadReadPdfRequest {
    file: Blob;
}

export interface UploadSpeechToTextRequest {
    file: Blob;
    model?: string;
    language?: string;
    prompt?: string;
}

/**
 * 
 */
export class UploadApi extends runtime.BaseAPI {

    /**
     * Accepts a multipart file upload and classifies/describes the image using the model configured in `TOOL_VISION_MODEL`. Max file size: 50 MB. 
     * Classify or describe an uploaded image
     */
    async uploadImageClassifyRaw(requestParameters: UploadImageClassifyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UploadImageClassify200Response>> {
        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling uploadImageClassify().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }

        if (requestParameters['prompt'] != null) {
            formParams.append('prompt', requestParameters['prompt'] as any);
        }

        if (requestParameters['model'] != null) {
            formParams.append('model', requestParameters['model'] as any);
        }

        const response = await this.request({
            path: `/upload/image-classify`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UploadImageClassify200ResponseFromJSON(jsonValue));
    }

    /**
     * Accepts a multipart file upload and classifies/describes the image using the model configured in `TOOL_VISION_MODEL`. Max file size: 50 MB. 
     * Classify or describe an uploaded image
     */
    async uploadImageClassify(requestParameters: UploadImageClassifyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UploadImageClassify200Response> {
        const response = await this.uploadImageClassifyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Accepts a multipart image upload and forwards it to the configured image processor (`IMAGE_PROCESSOR_URL/colorize`). Optional `prompt` and `negative_prompt` are passed through to the processor. Content negotiation: - `Accept: image/png` returns raw PNG bytes - otherwise returns JSON `{ image, duration_ms, model }` 
     * Colorize an uploaded image
     */
    async uploadImageColorizeRaw(requestParameters: UploadImageColorizeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ImageProcessorResponse>> {
        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling uploadImageColorize().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }

        if (requestParameters['prompt'] != null) {
            formParams.append('prompt', requestParameters['prompt'] as any);
        }

        if (requestParameters['negativePrompt'] != null) {
            formParams.append('negative_prompt', requestParameters['negativePrompt'] as any);
        }

        const response = await this.request({
            path: `/upload/image-colorize`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ImageProcessorResponseFromJSON(jsonValue));
    }

    /**
     * Accepts a multipart image upload and forwards it to the configured image processor (`IMAGE_PROCESSOR_URL/colorize`). Optional `prompt` and `negative_prompt` are passed through to the processor. Content negotiation: - `Accept: image/png` returns raw PNG bytes - otherwise returns JSON `{ image, duration_ms, model }` 
     * Colorize an uploaded image
     */
    async uploadImageColorize(requestParameters: UploadImageColorizeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ImageProcessorResponse> {
        const response = await this.uploadImageColorizeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Accepts a multipart image upload and forwards it to the configured image processor (`IMAGE_PROCESSOR_URL/sketch`). Optional `prompt` and `negative_prompt` are passed through to the processor. Content negotiation: - `Accept: image/png` returns raw PNG bytes - otherwise returns JSON `{ image, duration_ms, model }` 
     * Generate sketch/line-art from an uploaded image
     */
    async uploadImageSketchRaw(requestParameters: UploadImageSketchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ImageProcessorResponse>> {
        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling uploadImageSketch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }

        if (requestParameters['prompt'] != null) {
            formParams.append('prompt', requestParameters['prompt'] as any);
        }

        if (requestParameters['negativePrompt'] != null) {
            formParams.append('negative_prompt', requestParameters['negativePrompt'] as any);
        }

        const response = await this.request({
            path: `/upload/image-sketch`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ImageProcessorResponseFromJSON(jsonValue));
    }

    /**
     * Accepts a multipart image upload and forwards it to the configured image processor (`IMAGE_PROCESSOR_URL/sketch`). Optional `prompt` and `negative_prompt` are passed through to the processor. Content negotiation: - `Accept: image/png` returns raw PNG bytes - otherwise returns JSON `{ image, duration_ms, model }` 
     * Generate sketch/line-art from an uploaded image
     */
    async uploadImageSketch(requestParameters: UploadImageSketchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ImageProcessorResponse> {
        const response = await this.uploadImageSketchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Accepts a multipart PDF upload and returns the extracted text plus page count. Max file size: 50 MB. 
     * Extract text from an uploaded PDF
     */
    async uploadReadPdfRaw(requestParameters: UploadReadPdfRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UploadReadPdf200Response>> {
        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling uploadReadPdf().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }

        const response = await this.request({
            path: `/upload/read-pdf`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UploadReadPdf200ResponseFromJSON(jsonValue));
    }

    /**
     * Accepts a multipart PDF upload and returns the extracted text plus page count. Max file size: 50 MB. 
     * Extract text from an uploaded PDF
     */
    async uploadReadPdf(requestParameters: UploadReadPdfRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UploadReadPdf200Response> {
        const response = await this.uploadReadPdfRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Accepts a multipart audio upload and returns a transcript using `TOOL_STT_MODEL` (default `whisper`). Max file size: 50 MB. 
     * Transcribe an uploaded audio file
     */
    async uploadSpeechToTextRaw(requestParameters: UploadSpeechToTextRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UploadSpeechToText200Response>> {
        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling uploadSpeechToText().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }

        if (requestParameters['model'] != null) {
            formParams.append('model', requestParameters['model'] as any);
        }

        if (requestParameters['language'] != null) {
            formParams.append('language', requestParameters['language'] as any);
        }

        if (requestParameters['prompt'] != null) {
            formParams.append('prompt', requestParameters['prompt'] as any);
        }

        const response = await this.request({
            path: `/upload/speech-to-text`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UploadSpeechToText200ResponseFromJSON(jsonValue));
    }

    /**
     * Accepts a multipart audio upload and returns a transcript using `TOOL_STT_MODEL` (default `whisper`). Max file size: 50 MB. 
     * Transcribe an uploaded audio file
     */
    async uploadSpeechToText(requestParameters: UploadSpeechToTextRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UploadSpeechToText200Response> {
        const response = await this.uploadSpeechToTextRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
