/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  WorkflowRequest,
  WorkflowResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    WorkflowRequestFromJSON,
    WorkflowRequestToJSON,
    WorkflowResponseFromJSON,
    WorkflowResponseToJSON,
} from '../models/index';

export interface PostWorkflowRequest {
    workflowRequest: WorkflowRequest;
}

export interface PostWorkflowStreamRequest {
    workflowRequest: WorkflowRequest;
}

/**
 * 
 */
export class WorkflowApi extends runtime.BaseAPI {

    /**
     * Accepts an array of step task strings and runs each as an independent bounded `agent.run()` sub-call.  Each step has its own `maxStepsPerStep` iteration cap (defaulting to `AGENTS_MAX_STEPS`), so a misbehaving step cannot consume the entire budget.  ### Context carry modes (`carry`)  | Mode      | Behaviour | |-----------|-----------| | `none`    | Steps are fully isolated — no prior context forwarded. | | `summary` | A compact bullet-point summary of prior step results is prepended to each subsequent step prompt. **(default)** | | `full`    | The complete verbatim output of every prior step is appended. Context may grow quickly. |  Use `POST /workflow` when your outer loop is already structured as an ordered list and you want each step bounded independently. 
     * Run an explicit ordered list of steps sequentially
     */
    async postWorkflowRaw(requestParameters: PostWorkflowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WorkflowResponse>> {
        if (requestParameters['workflowRequest'] == null) {
            throw new runtime.RequiredError(
                'workflowRequest',
                'Required parameter "workflowRequest" was null or undefined when calling postWorkflow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/workflow`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WorkflowRequestToJSON(requestParameters['workflowRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkflowResponseFromJSON(jsonValue));
    }

    /**
     * Accepts an array of step task strings and runs each as an independent bounded `agent.run()` sub-call.  Each step has its own `maxStepsPerStep` iteration cap (defaulting to `AGENTS_MAX_STEPS`), so a misbehaving step cannot consume the entire budget.  ### Context carry modes (`carry`)  | Mode      | Behaviour | |-----------|-----------| | `none`    | Steps are fully isolated — no prior context forwarded. | | `summary` | A compact bullet-point summary of prior step results is prepended to each subsequent step prompt. **(default)** | | `full`    | The complete verbatim output of every prior step is appended. Context may grow quickly. |  Use `POST /workflow` when your outer loop is already structured as an ordered list and you want each step bounded independently. 
     * Run an explicit ordered list of steps sequentially
     */
    async postWorkflow(requestParameters: PostWorkflowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WorkflowResponse> {
        const response = await this.postWorkflowRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Same as `POST /workflow`, but streams lifecycle events as Server-Sent Events. The connection stays open until all steps complete.  SSE event types (in order): - `workflow_start` — before the first step; `{ stepCount }`. - `step_start`     — before each step; `{ index, task }`. - `step`           — inner agent iteration; `{ workflowIndex, step, action, thought }`. - `tool`           — tool result/error; `{ workflowIndex, tool, result? | error? }`. - `route`          — model routing decision; `{ workflowIndex, profile, model, reason }`. - `step_done`      — after each step; full `WorkflowStepResult` object. - `done`           — after all steps; full `WorkflowResponse` object. - `error`          — on fatal error; `{ error }`. 
     * Run a sequential workflow with SSE streaming
     */
    async postWorkflowStreamRaw(requestParameters: PostWorkflowStreamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['workflowRequest'] == null) {
            throw new runtime.RequiredError(
                'workflowRequest',
                'Required parameter "workflowRequest" was null or undefined when calling postWorkflowStream().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/workflow/stream`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WorkflowRequestToJSON(requestParameters['workflowRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Same as `POST /workflow`, but streams lifecycle events as Server-Sent Events. The connection stays open until all steps complete.  SSE event types (in order): - `workflow_start` — before the first step; `{ stepCount }`. - `step_start`     — before each step; `{ index, task }`. - `step`           — inner agent iteration; `{ workflowIndex, step, action, thought }`. - `tool`           — tool result/error; `{ workflowIndex, tool, result? | error? }`. - `route`          — model routing decision; `{ workflowIndex, profile, model, reason }`. - `step_done`      — after each step; full `WorkflowStepResult` object. - `done`           — after all steps; full `WorkflowResponse` object. - `error`          — on fatal error; `{ error }`. 
     * Run a sequential workflow with SSE streaming
     */
    async postWorkflowStream(requestParameters: PostWorkflowStreamRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.postWorkflowStreamRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
