/**
 * Core agent module — implements the reason → act → observe loop.
 *
 * The `Agent` class orchestrates the entire agentic workflow:
 *  1. Load relevant memory for the task.
 *  2. For each step (up to `MAX_STEPS`):
 *     a. Run `processInputStep` hooks (middleware before LLM call).
 *     b. Build a prompt with the task, accumulated context, and memory.
 *     c. Route to the best model via `routeModel`.
 *     d. Call the LLM and parse the JSON response with Zod.
 *     e. Run `processOutputStep` hooks (middleware after LLM call).
 *     f. Execute the chosen tool, or return if `action === "none"`.
 *     g. Append the tool result to context and repeat.
 *
 * Design principles:
 *  - **No magic** — every decision is traceable via structured logs and events.
 *  - **Resilient** — bad JSON and unknown tools are recovered, not crashed.
 *  - **Observable** — every significant state change emits a typed event.
 *  - **Extensible** — processors can intercept input/output at each step.
 *
 * @module agent/agent
 */

import { generateWithMetadata, generate } from '../llm/ollama';
import { addMemory, getMemory } from '../memory/memory';
import { emit } from '../events/bus';
import type { ITool } from '../tools';
import { logger } from '../logger/logger';
import { resolveModel, stripCodeFences } from '../shared';
import { routeModel } from './model-router';
import type { ModelProfile } from './model-router';
import { agentStepSchema } from './schemas';
import type { AgentStep } from './schemas';
import type {
    IProcessor,
    IProcessInputStepArgs,
    IProcessOutputStepArgs
} from '../processors/types';
import { writeDiagnosticLog, cleanupOldLogs } from '../diagnostics';
import type { IDiagnosticEntry } from '../diagnostics';
import { saveAgentRun } from '../persistence/db';
import type { IToolCall } from '../persistence/types';
import type { IGenerateResult } from '../llm/ollama';

/**
 * Maximum number of reasoning iterations before the agent gives up.
 * Configurable via the `AGENTS_MAX_STEPS` environment variable.
 */
const MAX_STEPS = Number.parseInt(process.env.AGENTS_MAX_STEPS ?? '20', 10);

/**
 * Directory where diagnostic Markdown files are written.
 * Kept in sync with the writer's own default.
 */
const DIAGNOSTIC_LOG_DIR = process.env.DIAGNOSTIC_LOG_DIR ?? 'data/diagnostics';

/**
 * Auto-prune threshold for diagnostic log files.
 */
const DIAGNOSTIC_LOG_MAX_FILES = Number.parseInt(process.env.DIAGNOSTIC_LOG_MAX_FILES ?? '100', 10);

/**
 * Structured metadata produced by one `Agent.run()` execution.
 */
export interface IAgentRunMeta {
    /** ISO timestamp indicating when this run started. */
    startedAt: string;
    /** Wall-clock duration in milliseconds for the full run. */
    durationMs: number;
    /** Number of LLM reasoning steps executed. */
    steps: number;
    /** Number of tool calls executed (success + failure). */
    toolCalls: number;
    /** Models used by this run (deduplicated, execution order preserved). */
    models: string[];
    /** Effective profile when a single profile is identifiable. */
    profile?: ModelProfile;
    /** Aggregated prompt tokens when reported by the provider. */
    promptTokens?: number;
    /** Aggregated completion tokens when reported by the provider. */
    completionTokens?: number;
    /** Aggregated total tokens when both prompt/completion totals are known. */
    totalTokens?: number;
    /** Final context length in characters. */
    contextLength: number;
    /** Whether semantic memory retrieval returned entries. */
    memoryUsed: boolean;
}

/**
 * Full result returned by `Agent.run()`.
 */
export interface IAgentRunResult {
    /** Final answer generated by the agent loop. */
    answer: string;
    /** Operational metadata captured during the run. */
    meta: IAgentRunMeta;
}

/**
 * Mutable token counters accumulated across LLM steps.
 * Extracted to avoid scattering nullable arithmetic throughout `run()`.
 */
interface ITokenAccumulator {
    promptTokens: number | undefined;
    completionTokens: number | undefined;
}

/**
 * The core agent — wraps tools, processors, memory, and an LLM into a
 * single `run()` method that executes an agentic reasoning loop.
 *
 * Usage:
 * ```typescript
 * const agent = new Agent([readFileTool, shellTool]);
 * const run = await agent.run("List all TypeScript files in src/");
 * const answer = run.answer;
 * ```
 */
export class Agent {
    /** Registered processors (middleware hooks), invoked in order. */
    private readonly processors: IProcessor[] = [];

    /**
     * Create a new Agent.
     *
     * @param tools - The set of tools the agent is allowed to use.
     *                The agent loop discovers tools from this array.
     */
    constructor(private readonly tools: ITool[]) {}

    /**
     * Register a processor whose hooks will be called at each agent step.
     *
     * Processors are invoked in registration order.  A processor may
     * return a modified argument object to influence the agent, or
     * return `void` / `undefined` to leave the arguments unchanged.
     *
     * @param processor - The processor to register.
     * @returns `this` for fluent chaining.
     */
    addProcessor(processor: IProcessor): this {
        this.processors.push(processor);
        return this;
    }

    /* ── Private helpers (DRY + SRP extractions) ─────────────────────── */

    /**
     * Accumulate token counts from an LLM result into a mutable accumulator.
     *
     * @param accumulator - The token accumulator to mutate.
     * @param llmResult   - The LLM response containing optional token counts.
     */
    private static accumulateTokens(
        accumulator: ITokenAccumulator,
        llmResult: IGenerateResult
    ): void {
        if (typeof llmResult.promptEvalCount === 'number') {
            accumulator.promptTokens = (accumulator.promptTokens ?? 0) + llmResult.promptEvalCount;
        }
        if (typeof llmResult.evalCount === 'number') {
            accumulator.completionTokens =
                (accumulator.completionTokens ?? 0) + llmResult.evalCount;
        }
    }

    /**
     * Log and emit an LLM error, then re-throw.
     *
     * @param error - The caught error.
     * @param step  - Current agent step index.
     * @throws Always re-throws the original error.
     */
    private static handleLlmError(error: unknown, step: number): never {
        logger.error('agent_llm_call_failed', {
            component: 'agent',
            step,
            error: String(error)
        });
        emit({ type: 'agent:error', payload: { step, error: String(error) } });
        throw error;
    }

    /**
     * Persist an agent run to PostgreSQL (fail-open — never throws).
     *
     * @param input - The full run input for `saveAgentRun`.
     */
    private static async persistRun(input: Parameters<typeof saveAgentRun>[0]): Promise<void> {
        await saveAgentRun(input).catch((error: unknown) =>
            logger.warn('agent_persist_failed', {
                component: 'agent',
                error: String(error)
            })
        );
    }

    /**
     * Write diagnostics to disk and prune old logs if entries were collected.
     *
     * @param entries - Diagnostic entries from this run.
     * @param task    - The user's task description (used in the log filename).
     * @param summary - Optional AI commentary appended to the log.
     */
    private static async writeDiagnostics(
        entries: IDiagnosticEntry[],
        task: string,
        summary?: string
    ): Promise<void> {
        if (entries.length === 0 && !summary) return;
        await writeDiagnosticLog(entries, task, summary)
            .then(async (logPath) => {
                await cleanupOldLogs(DIAGNOSTIC_LOG_DIR, DIAGNOSTIC_LOG_MAX_FILES);
                logger.info('agent_diagnostic_log_written', { component: 'agent', logPath });
            })
            .catch((error: unknown) =>
                logger.warn('agent_diagnostic_log_failed', {
                    component: 'agent',
                    error: String(error)
                })
            );
    }

    /**
     * Run all registered input processors in order.
     *
     * @param args - The initial input step arguments.
     * @returns The (possibly modified) input step arguments.
     */
    private async runInputProcessors(args: IProcessInputStepArgs): Promise<IProcessInputStepArgs> {
        let result = args;
        for (const proc of this.processors) {
            if (proc.processInputStep) {
                const modified = await proc.processInputStep(result);
                if (modified) result = modified;
            }
        }
        return result;
    }

    /**
     * Run all registered output processors in order.
     *
     * @param args - The initial output step arguments.
     * @returns The (possibly modified) output step arguments.
     */
    private async runOutputProcessors(
        args: IProcessOutputStepArgs
    ): Promise<IProcessOutputStepArgs> {
        let result = args;
        for (const proc of this.processors) {
            if (proc.processOutputStep) {
                const modified = await proc.processOutputStep(result);
                if (modified) result = modified;
            }
        }
        return result;
    }

    /**
     * Assemble the full prompt string sent to the LLM at each step.
     *
     * @param task    - The user's task description.
     * @param context - Accumulated context from prior steps.
     * @param memory  - Relevant memory strings.
     * @returns The fully assembled prompt string.
     */
    private buildPrompt(task: string, context: string, memory: string[]): string {
        const memoryBlock = memory.length > 0 ? `Recent memory:\n${memory.join('\n')}\n\n` : '';
        const contextBlock = context ? `Context so far:\n${context}\n\n` : '';
        const toolList = this.tools.map((t) => `- ${t.name}: ${t.description}`).join('\n');

        return (
            `You are an AI agent with access to tools.\n\n` +
            `Task:\n${task}\n\n` +
            memoryBlock +
            contextBlock +
            `Available tools:\n${toolList}\n\n` +
            `Respond ONLY with a single valid JSON object — no markdown, no extra text:\n` +
            `{\n` +
            `  "thought": "your reasoning or final answer",\n` +
            `  "action": "tool_name or none",\n` +
            `  "input": {}\n` +
            `}\n\n` +
            `Rules:\n` +
            `- Only use a tool when you genuinely need to read a file, run a command, or access external data.\n` +
            `- Use action "none" when the task is fully complete.`
        );
    }

    /* ── Public API ──────────────────────────────────────────────────── */

    /**
     * Execute the full agentic loop for a given task.
     *
     * @param task    - The user's natural-language task description.
     * @param options - Optional configuration (e.g. `{ profile: "code", maxSteps: 10 }`).
     * @returns The agent's final answer and operational metadata.
     */
    async run(
        task: string,
        options?: { profile?: ModelProfile; maxSteps?: number }
    ): Promise<IAgentRunResult> {
        const runStartedAt = Date.now();
        const startTime = new Date();
        let context = '';
        const diagnosticEntries: IDiagnosticEntry[] = [];
        const toolCalls: IToolCall[] = [];
        const modelsUsed = new Set<string>();
        const profilesUsed = new Set<ModelProfile>();
        const tokens: ITokenAccumulator = {
            promptTokens: undefined,
            completionTokens: undefined
        };
        let llmSteps = 0;

        const effectiveMaxSteps =
            typeof options?.maxSteps === 'number' && options.maxSteps > 0
                ? options.maxSteps
                : MAX_STEPS;

        logger.info('agent_run_started', {
            component: 'agent',
            task,
            taskLength: task.length,
            maxSteps: effectiveMaxSteps,
            toolCount: this.tools.length
        });

        /* Load semantic + recent memory relevant to this task. */
        const memoryStartedAt = Date.now();
        const memory = await getMemory(task);
        logger.info('agent_memory_loaded', {
            component: 'agent',
            memoryCount: memory.length,
            durationMs: Date.now() - memoryStartedAt
        });

        emit({ type: 'agent:start', payload: { task } });

        const buildRunMeta = (): IAgentRunMeta => {
            const totalTokens =
                typeof tokens.promptTokens === 'number' &&
                typeof tokens.completionTokens === 'number'
                    ? tokens.promptTokens + tokens.completionTokens
                    : undefined;
            const profile =
                options?.profile ?? (profilesUsed.size === 1 ? [...profilesUsed][0] : undefined);
            return {
                startedAt: startTime.toISOString(),
                durationMs: Date.now() - runStartedAt,
                steps: llmSteps,
                toolCalls: toolCalls.length,
                models: [...modelsUsed],
                profile,
                promptTokens: tokens.promptTokens,
                completionTokens: tokens.completionTokens,
                totalTokens,
                contextLength: context.length,
                memoryUsed: memory.length > 0
            };
        };

        const persistInput = (output: string, status: 'completed' | 'max_steps') => ({
            task,
            agentProfile: options?.profile ?? null,
            output,
            context,
            memory,
            startTime,
            endTime: new Date(),
            durationMs: Date.now() - runStartedAt,
            toolCalls,
            diagnosticEntries,
            status
        });

        for (let step = 0; step < effectiveMaxSteps; step++) {
            const stepStartedAt = Date.now();

            // ── Run input processors ─────────────────────────────────────────
            const inputArgs = await this.runInputProcessors({
                task,
                context,
                memory,
                stepNumber: step,
                tools: this.tools.map((t) => t.name)
            });

            // ── Route model ──────────────────────────────────────────────────
            const route = await routeModel({
                task: inputArgs.task,
                context: inputArgs.context,
                step,
                forcedProfile: options?.profile,
                contextLength: inputArgs.context.length,
                cumulativeDurationMs: Date.now() - runStartedAt
            }).catch((error: unknown) => Agent.handleLlmError(error, step));

            profilesUsed.add(route.profile);
            emit({
                type: 'agent:model_routed',
                payload: {
                    step,
                    profile: route.profile,
                    model: route.model,
                    reason: route.reason
                }
            });

            // ── Direct-answer shortcut: no tools available ───────────────────
            if (step === 0 && !inputArgs.context && this.tools.length === 0) {
                const memoryBlock =
                    inputArgs.memory.length > 0
                        ? `Relevant context:\n${inputArgs.memory.join('\n')}\n\n`
                        : '';
                const directPrompt = `${memoryBlock}Task:\n${inputArgs.task}\n\nAnswer concisely and directly.`;
                logger.info('agent_direct_answer', {
                    component: 'agent',
                    step,
                    reason: route.reason
                });

                const directResult = await generateWithMetadata(directPrompt, {
                    model: route.model,
                    options: route.options
                }).catch((error: unknown) => Agent.handleLlmError(error, step));

                llmSteps += 1;
                modelsUsed.add(directResult.model ?? route.model);
                Agent.accumulateTokens(tokens, directResult);

                const answer = directResult.response.trim();
                await addMemory(`Task: ${task} → ${answer}`);
                emit({ type: 'agent:done', payload: { thought: answer } });
                await Agent.persistRun(persistInput(answer, 'completed'));
                return { answer, meta: buildRunMeta() };
            }

            // ── Build prompt and call LLM ────────────────────────────────────
            const prompt = this.buildPrompt(inputArgs.task, inputArgs.context, inputArgs.memory);
            logger.info('agent_step_started', {
                component: 'agent',
                step,
                contextLength: inputArgs.context.length,
                promptLength: prompt.length,
                promptPreview: prompt.length > 300 ? prompt.slice(0, 300) + '…' : prompt
            });

            const llmResult = await generateWithMetadata(prompt, {
                model: route.model,
                options: route.options
            }).catch((error: unknown) => Agent.handleLlmError(error, step));

            llmSteps += 1;
            modelsUsed.add(llmResult.model ?? route.model);
            Agent.accumulateTokens(tokens, llmResult);
            logger.info('agent_llm_response_received', {
                component: 'agent',
                step,
                responseLength: llmResult.response.length,
                durationMs: Date.now() - runStartedAt,
                routedProfile: route.profile,
                routedReason: route.reason,
                model: llmResult.model
            });

            const response = llmResult.response;

            // ── Parse the LLM response ───────────────────────────────────────
            let parsed: AgentStep;
            try {
                const cleaned = stripCodeFences(response);
                parsed = agentStepSchema.parse(JSON.parse(cleaned));
            } catch {
                context +=
                    '\nYour previous response was not valid JSON. ' +
                    'Please respond ONLY with a single valid JSON object.';
                logger.warn('agent_invalid_json_response', {
                    component: 'agent',
                    step,
                    responseLength: response.length,
                    contextLength: context.length
                });
                diagnosticEntries.push({
                    timestamp: new Date().toISOString(),
                    step,
                    severity: 'warn',
                    category: 'json',
                    message: 'Invalid JSON response from LLM — asking model to self-correct.',
                    metadata: { responseLength: response.length }
                });
                continue;
            }

            logger.info('agent_step_parsed', {
                component: 'agent',
                step,
                action: parsed.action,
                thoughtLength: parsed.thought.length
            });
            emit({ type: 'agent:step', payload: { step, parsed } });

            // ── Run output processors ────────────────────────────────────────
            const outputArgs = await this.runOutputProcessors({
                task,
                stepNumber: step,
                text: response,
                thought: parsed.thought,
                action: parsed.action,
                toolInput: parsed.input
            });
            parsed = {
                thought: outputArgs.thought,
                action: outputArgs.action,
                input: outputArgs.toolInput
            };

            // ── Done — no tool action needed ─────────────────────────────────
            if (parsed.action === 'none') {
                await addMemory(`Task: ${task} → ${parsed.thought}`);
                logger.info('agent_run_completed', {
                    component: 'agent',
                    step,
                    durationMs: Date.now() - runStartedAt,
                    finalThoughtLength: parsed.thought.length
                });
                emit({ type: 'agent:done', payload: { thought: parsed.thought } });
                await Agent.writeDiagnostics(diagnosticEntries, task);
                await Agent.persistRun(persistInput(parsed.thought, 'completed'));
                return { answer: parsed.thought, meta: buildRunMeta() };
            }

            // ── Find and execute the requested tool ──────────────────────────
            const tool = this.tools.find((t) => t.name === parsed.action);
            if (!tool) {
                logger.warn('agent_unknown_tool', {
                    component: 'agent',
                    step,
                    action: parsed.action,
                    availableTools: this.tools.map((t) => t.name)
                });
                context +=
                    `\nTool "${parsed.action}" does not exist. ` +
                    `Available tools: ${this.tools.map((t) => t.name).join(', ')}.`;
                diagnosticEntries.push({
                    timestamp: new Date().toISOString(),
                    step,
                    severity: 'warn',
                    category: 'tool',
                    message: `Unknown tool requested: "${parsed.action}".`,
                    metadata: { availableTools: this.tools.map((t) => t.name) }
                });
                continue;
            }

            const toolStartedAt = Date.now();
            const toolResult = await tool
                .execute(parsed.input)
                .then((result) => {
                    const durationMs = Date.now() - toolStartedAt;
                    logger.info('agent_tool_executed', {
                        component: 'agent',
                        step,
                        tool: parsed.action,
                        durationMs
                    });
                    toolCalls.push({
                        tool: parsed.action,
                        step,
                        input: parsed.input,
                        result,
                        success: true,
                        durationMs
                    });
                    return { success: true as const, result };
                })
                .catch((error: unknown) => {
                    context += `\nTool "${parsed.action}" failed: ${String(error)}`;
                    const durationMs = Date.now() - toolStartedAt;
                    logger.warn('agent_tool_failed', {
                        component: 'agent',
                        step,
                        tool: parsed.action,
                        error: String(error)
                    });
                    emit({
                        type: 'tool:error',
                        payload: { tool: parsed.action, error: String(error) }
                    });
                    diagnosticEntries.push({
                        timestamp: new Date().toISOString(),
                        step,
                        severity: 'error',
                        category: 'tool',
                        message: `Tool "${parsed.action}" failed: ${String(error)}`,
                        metadata: { tool: parsed.action }
                    });
                    toolCalls.push({
                        tool: parsed.action,
                        step,
                        input: parsed.input,
                        result: null,
                        success: false,
                        error: String(error),
                        durationMs
                    });
                    return { success: false as const };
                });
            if (!toolResult.success) continue;

            emit({
                type: 'tool:result',
                payload: { tool: parsed.action, result: toolResult.result }
            });
            context += `\nStep ${step} — "${parsed.action}" returned: ${JSON.stringify(toolResult.result)}`;
            logger.info('agent_step_finished', {
                component: 'agent',
                step,
                durationMs: Date.now() - stepStartedAt,
                contextLength: context.length
            });
        }

        /* Loop exhausted without the model returning action "none". */
        logger.warn('agent_max_steps_reached', {
            component: 'agent',
            durationMs: Date.now() - runStartedAt,
            task
        });

        /* Self-debugging summary using the fast model. */
        const debugPrompt =
            `You are a debugging assistant.\n` +
            `The agent loop exhausted its steps without completing the task.\n\n` +
            `Task:\n${task}\n\n` +
            `Context (what happened):\n${context}\n\n` +
            `Summarise concisely:\n` +
            `1. What was tried.\n` +
            `2. Where it got stuck.\n` +
            `3. Suggestions for what to try next.`;
        const summary = await generate(debugPrompt, {
            model: resolveModel('fast'),
            stream: false
        })
            .then((result) => result.trim() || 'Max steps reached without a conclusive answer.')
            .catch((error: unknown) => {
                logger.warn('agent_self_debug_failed', {
                    component: 'agent',
                    error: String(error)
                });
                return 'Max steps reached without a conclusive answer.';
            });

        await addMemory(`Task: ${task} → [MAX_STEPS] ${summary}`).catch((error: unknown) =>
            logger.warn('agent_memory_add_failed', {
                component: 'agent',
                error: String(error)
            })
        );

        await Agent.writeDiagnostics(diagnosticEntries, task, summary);
        await Agent.persistRun(persistInput(summary, 'max_steps'));

        emit({
            type: 'agent:max_steps',
            payload: { task, summary, diagnosticFile: '' }
        });
        return { answer: summary, meta: buildRunMeta() };
    }
}
