/**
 * Core agent module — implements the reason → act → observe loop.
 *
 * The `Agent` class orchestrates the entire agentic workflow:
 *  1. Load relevant memory for the task.
 *  2. For each step (up to `MAX_STEPS`):
 *     a. Run `processInputStep` hooks (middleware before LLM call).
 *     b. Build a prompt with the task, accumulated context, and memory.
 *     c. Route to the best model via `routeModel`.
 *     d. Call the LLM and parse the JSON response with Zod.
 *     e. Run `processOutputStep` hooks (middleware after LLM call).
 *     f. Execute the chosen tool, or return if `action === "none"`.
 *     g. Append the tool result to context and repeat.
 *
 * Design principles:
 *  - **No magic** — every decision is traceable via structured logs and events.
 *  - **Resilient** — bad JSON and unknown tools are recovered, not crashed.
 *  - **Observable** — every significant state change emits a typed event.
 *  - **Extensible** — processors can intercept input/output at each step.
 *
 * @module agent/agent
 */

import { generateWithMetadata } from "../llm/ollama";
import { addMemory, getMemory } from "../memory/memory";
import { emit } from "../events/bus";
import type { Tool } from "../tools";
import { getLogger } from "../logger/logger";
import { routeModel } from "./model-router";
import type { ModelProfile } from "./model-router";
import { agentStepSchema } from "./schemas";
import type { AgentStep } from "./schemas";
import type {
  Processor,
  ProcessInputStepArgs,
  ProcessOutputStepArgs,
} from "../processors/types";
import { envInt } from "../shared";
import { writeDiagnosticLog } from "../diagnostics";
import type { DiagnosticEntry, DiagnosticTimelineEntry, DiagnosticError } from "../diagnostics";

/**
 * Maximum number of reasoning iterations before the agent gives up.
 * Configurable via the `AGENTS_MAX_STEPS` environment variable.
 */
const MAX_STEPS = Number.parseInt(process.env.AGENTS_MAX_STEPS ?? "5", 10);

/**
 * Maximum context size in characters before the agent pauses and asks the user.
 * Mirrors the budget ceiling defined in `model-router.ts`.
 * Configurable via `AGENT_BUDGET_MAX_CONTEXT_CHARS`.
 */
const BUDGET_MAX_CONTEXT_CHARS = envInt(process.env.AGENT_BUDGET_MAX_CONTEXT_CHARS, 50_000);

/**
 * Characters of the most-recent context to include in the overflow condensation
 * prompt.  We take a trailing window (rather than the full context) because
 * the summarisation model also has a context limit.  16 % of the budget ceiling
 * gives ~8000 chars by default, which comfortably fits in any small LLM.
 */
const OVERFLOW_SUMMARY_CONTEXT_WINDOW = Math.floor(BUDGET_MAX_CONTEXT_CHARS * 0.16);

/**
 * Fallback context window used when the overflow summarisation LLM call fails.
 * Half of the normal window: a more conservative truncation that gives the
 * caller the most recent context at a smaller size.
 */
const OVERFLOW_FALLBACK_CONTEXT_WINDOW = Math.floor(OVERFLOW_SUMMARY_CONTEXT_WINDOW / 2);

/**
 * Characters of context to send to the max-steps failure-summary LLM.
 * Slightly smaller than the overflow window: at max_steps the context is
 * already at its accumulated maximum so we cap to a sane LLM input size.
 */
const MAX_STEPS_SUMMARY_CONTEXT_WINDOW = Math.floor(BUDGET_MAX_CONTEXT_CHARS * 0.12);

/**
 * Fast/cheap Ollama model used for summarisation calls (max_steps, context overflow).
 * Resolved from the same env chain as the `fast` profile in `model-router.ts`.
 */
const FAST_SUMMARY_MODEL =
  process.env.AGENT_MODEL_FAST ?? process.env.OLLAMA_MODEL ?? "llama3";

const log = getLogger("agent");

/* ── Public result type ──────────────────────────────────────────────── */

/**
 * Status codes returned by `Agent.run()`.
 *
 * - `completed`        — the agent finished the task (`action: "none"`).
 * - `max_steps`        — the agent exhausted its step budget.
 * - `context_overflow` — the accumulated context exceeded the size ceiling;
 *                        the caller should decide whether to continue with
 *                        the condensed context or rephrase the task.
 */
export type AgentRunStatus = "completed" | "max_steps" | "context_overflow";

/**
 * Structured result returned by `Agent.run()`.
 *
 * All callers must now handle the `status` field to distinguish between
 * a successful completion and the two non-completion states.
 */
export interface AgentRunResult {
  /**
   * How the run ended.
   * - `completed`        — normal completion; `result` holds the final answer.
   * - `max_steps`        — loop exhausted; `result` holds the AI-generated failure summary.
   * - `context_overflow` — context too large; `result` holds a condensed summary.
   */
  status: AgentRunStatus;

  /**
   * The primary text output of the run.
   * Content varies by status:
   * - `completed`        — the agent's final thought / answer.
   * - `max_steps`        — a structured failure summary generated by the LLM.
   * - `context_overflow` — a condensed summary of findings so far.
   */
  result: string;

  /**
   * Condensed context string that the caller may pass back as `resumeContext`
   * to continue the run with reduced context.
   * Present only when `status === "context_overflow"`.
   */
  condensedContext?: string;

  /** The original task passed to `run()`. Present when `status !== "completed"`. */
  originalTask?: string;

  /** LLM-generated suggestion for the human operator. Present on non-completion statuses. */
  suggestion?: string;
}

/**
 * The core agent — wraps tools, processors, memory, and an LLM into a
 * single `run()` method that executes an agentic reasoning loop.
 *
 * Usage:
 * ```typescript
 * const agent = new Agent([readFileTool, shellTool]);
 * const answer = await agent.run("List all TypeScript files in src/");
 * ```
 */
export class Agent {
  /** Registered processors (middleware hooks), invoked in order. */
  private readonly processors: Processor[] = [];

  /**
   * Create a new Agent.
   *
   * @param tools - The set of tools the agent is allowed to use.
   *                The agent loop discovers tools from this array.
   */
  constructor(private readonly tools: Tool[]) {}

  /**
   * Register a processor whose hooks will be called at each agent step.
   *
   * Processors are invoked in registration order.  A processor may
   * return a modified argument object to influence the agent, or
   * return `void` / `undefined` to leave the arguments unchanged.
   *
   * @param processor - The processor to register.
   * @returns `this` for fluent chaining.
   */
  addProcessor(processor: Processor): this {
    this.processors.push(processor);
    return this;
  }

  /**
   * Execute the full agentic loop for a given task.
   *
   * Optionally accepts a `profile` override that forces the model
   * router to use a specific profile for every step, bypassing
   * automatic routing.
   *
   * When `resumeContext` is provided (from a previous `context_overflow`
   * response), it is injected as the initial context so the agent can
   * continue from where it left off with a condensed starting point.
   *
   * @param task    - The user's natural-language task description.
   * @param options - Optional configuration (e.g. `{ profile: "code" }`).
   * @returns A structured `AgentRunResult` describing how the run ended.
   */
  async run(
    task: string,
    options?: { profile?: ModelProfile; resumeContext?: string },
  ): Promise<AgentRunResult> {
    const runStartedAt = Date.now();
    let context = "";
    let cumulativeDurationMs = 0;

    /* Tracking structures for diagnostics and timeline. */
    const timeline: DiagnosticTimelineEntry[] = [];
    const diagnosticErrors: DiagnosticError[] = [];
    const toolsUsedSet = new Set<string>();

    log.info("agent_run_started", {
      task,
      taskLength: task.length,
      maxSteps: MAX_STEPS,
      toolCount: this.tools.length,
    });

    /* Inject resume context when the caller provides one (from a previous
     * context_overflow pause). This allows the agent to continue a task
     * with a condensed context instead of starting from scratch. */
    if (options?.resumeContext) {
      context = options.resumeContext;
      log.info("agent_resume_context_injected", {
        resumeContextLength: options.resumeContext.length,
      });
    }

    /* Load semantic + recent memory relevant to this task. */
    const memoryStartedAt = Date.now();
    const memory = await getMemory(task);
    log.info("agent_memory_loaded", {
      memoryCount: memory.length,
      durationMs: Date.now() - memoryStartedAt,
    });

    emit({ type: "agent:start", payload: { task } });

    for (let step = 0; step < MAX_STEPS; step++) {
      const stepStartedAt = Date.now();

      // ── Context overflow check ───────────────────────────────────────
      if (context.length > BUDGET_MAX_CONTEXT_CHARS) {
        log.warn("agent_context_overflow", {
          step,
          contextLength: context.length,
          budgetMaxContextChars: BUDGET_MAX_CONTEXT_CHARS,
        });

        /* Generate a condensed summary of findings so far. */
        const overflowPrompt =
          `The following accumulated context from an ongoing task has become too large.\n` +
          `Task: ${task}\n\n` +
          `Context:\n${context.slice(-OVERFLOW_SUMMARY_CONTEXT_WINDOW)}\n\n` +
          `Please provide a concise summary (max 2000 characters) of the key findings, ` +
          `decisions made, and current state. This summary will replace the full context.`;

        let condensedContext = "";
        try {
          const summaryResult = await generateWithMetadata(overflowPrompt, {
            model: FAST_SUMMARY_MODEL,
          });
          condensedContext = summaryResult.response.trim();
        } catch (e) {
          /* Summarisation LLM failed — fall back to a plain tail truncation.
           * The caller receives raw context (not an AI-generated summary).
           * This degraded path is indicated by the log warning below. */
          log.warn("agent_context_overflow_summary_failed_using_truncation", {
            error: String(e),
            fallbackWindowChars: OVERFLOW_FALLBACK_CONTEXT_WINDOW,
          });
          condensedContext = context.slice(-OVERFLOW_FALLBACK_CONTEXT_WINDOW);
        }

        emit({
          type: "agent:context_overflow",
          payload: { step, task, contextLength: context.length },
        });

        /* Write a diagnostic log for this overflow event. */
        const overflowEntry: DiagnosticEntry = {
          timestamp: new Date().toISOString(),
          task,
          outcome: "context_overflow",
          stepsCompleted: step,
          contextSnapshot: context,
          toolsUsed: [...toolsUsedSet],
          timeline,
          errors: diagnosticErrors,
          failureReason: `Context size (${context.length} chars) exceeded budget ceiling (${BUDGET_MAX_CONTEXT_CHARS} chars).`,
          aiCommentary: condensedContext,
          suggestion:
            "You can continue with reduced context, rephrase your task, or break it into smaller sub-tasks.",
        };
        await writeDiagnosticLog(overflowEntry);

        return {
          status: "context_overflow",
          result: condensedContext,
          condensedContext,
          originalTask: task,
          suggestion:
            "You can continue with reduced context by POSTing to /run with " +
            '"resumeContext" set to the "condensedContext" value, rephrase your task, ' +
            "or break it into smaller sub-tasks.",
        };
      }

      // ── Run input processors ─────────────────────────────────────────
      let inputArgs: ProcessInputStepArgs = {
        task,
        context,
        memory,
        stepNumber: step,
        tools: this.tools.map((t) => t.name),
      };
      for (const proc of this.processors) {
        if (proc.processInputStep) {
          const result = await proc.processInputStep(inputArgs);
          if (result) inputArgs = result;
        }
      }

      const prompt = this.buildPrompt(
        inputArgs.task,
        inputArgs.context,
        inputArgs.memory,
      );
      log.info("agent_step_started", {
        step,
        contextLength: inputArgs.context.length,
        promptLength: prompt.length,
        promptPreview:
          prompt.length > 300 ? prompt.slice(0, 300) + "…" : prompt,
      });

      // ── Call the LLM ─────────────────────────────────────────────────
      let response: string;
      let stepProfile = "default";
      try {
        const route = await routeModel({
          task: inputArgs.task,
          context: inputArgs.context,
          step,
          contextLength: inputArgs.context.length,
          cumulativeDurationMs,
          forcedProfile: options?.profile,
        });
        stepProfile = route.profile;
        emit({
          type: "agent:model_routed",
          payload: {
            step,
            profile: route.profile,
            model: route.model,
            reason: route.reason,
          },
        });

        const llmStartedAt = Date.now();
        const llmResult = await generateWithMetadata(prompt, {
          model: route.model,
          options: route.options,
        });
        response = llmResult.response;
        log.info("agent_llm_response_received", {
          step,
          responseLength: response.length,
          durationMs: Date.now() - llmStartedAt,
          routedProfile: route.profile,
          routedReason: route.reason,
          model: llmResult.model,
          done: llmResult.done,
          doneReason: llmResult.doneReason,
          totalDurationNs: llmResult.totalDurationNs,
          loadDurationNs: llmResult.loadDurationNs,
          promptEvalCount: llmResult.promptEvalCount,
          promptEvalDurationNs: llmResult.promptEvalDurationNs,
          evalCount: llmResult.evalCount,
          evalDurationNs: llmResult.evalDurationNs,
        });
      } catch (error) {
        const stepDurationMs = Date.now() - stepStartedAt;
        cumulativeDurationMs += stepDurationMs;
        diagnosticErrors.push({ step, type: "llm_error", detail: String(error) });
        timeline.push({
          step,
          profile: stepProfile,
          action: "llm_call",
          durationMs: stepDurationMs,
          status: "failed",
          detail: String(error),
        });
        log.error("agent_llm_call_failed", { step, error: String(error) });
        emit({ type: "agent:error", payload: { step, error: String(error) } });
        throw error;
      }

      // ── Parse the LLM response with Zod schema validation ────────────
      let parsed: AgentStep;
      try {
        /* Strip markdown code fences that some models wrap around JSON. */
        const cleaned = response.replace(/```(?:json)?\n?/g, "").trim();
        parsed = agentStepSchema.parse(JSON.parse(cleaned));
      } catch {
        /* Give the model a chance to self-correct on the next iteration. */
        context +=
          "\nYour previous response was not valid JSON. " +
          "Please respond ONLY with a single valid JSON object.";
        const stepDurationMs = Date.now() - stepStartedAt;
        cumulativeDurationMs += stepDurationMs;
        diagnosticErrors.push({ step, type: "invalid_json", detail: "LLM returned non-JSON or schema mismatch" });
        timeline.push({
          step,
          profile: stepProfile,
          action: "invalid_json",
          durationMs: stepDurationMs,
          status: "invalid_json",
          detail: "LLM returned non-JSON or schema mismatch; asking model to self-correct",
        });
        log.warn("agent_invalid_json_response", {
          step,
          responseLength: response.length,
          contextLength: context.length,
        });
        continue;
      }

      log.info("agent_step_parsed", {
        step,
        action: parsed.action,
        thoughtLength: parsed.thought.length,
      });
      emit({ type: "agent:step", payload: { step, parsed } });

      // ── Run output processors ────────────────────────────────────────
      let outputArgs: ProcessOutputStepArgs = {
        stepNumber: step,
        text: response,
        thought: parsed.thought,
        action: parsed.action,
        toolInput: parsed.input,
      };
      for (const proc of this.processors) {
        if (proc.processOutputStep) {
          const result = await proc.processOutputStep(outputArgs);
          if (result) outputArgs = result;
        }
      }
      /* Reflect any processor overrides back into the parsed step. */
      parsed = {
        thought: outputArgs.thought,
        action: outputArgs.action,
        input: outputArgs.toolInput,
      };

      // ── Done — no tool action needed ─────────────────────────────────
      if (parsed.action === "none") {
        const stepDurationMs = Date.now() - stepStartedAt;
        cumulativeDurationMs += stepDurationMs;
        timeline.push({
          step,
          profile: stepProfile,
          action: "none",
          durationMs: stepDurationMs,
          status: "none",
        });

        await addMemory(`Task: ${task} → ${parsed.thought}`);
        log.info("agent_run_completed", {
          step,
          durationMs: Date.now() - runStartedAt,
          finalThoughtLength: parsed.thought.length,
        });
        emit({ type: "agent:done", payload: { thought: parsed.thought } });

        /* Write a diagnostic log for runs that had recoveries
         * (tool errors, invalid JSON, unknown tools) even though they
         * eventually succeeded — useful for review and tuning. */
        if (diagnosticErrors.length > 0) {
          const successWithRecoveryEntry: DiagnosticEntry = {
            timestamp: new Date().toISOString(),
            task,
            outcome: "success",
            stepsCompleted: step + 1,
            contextSnapshot: context,
            toolsUsed: [...toolsUsedSet],
            timeline,
            errors: diagnosticErrors,
            aiCommentary:
              `The agent succeeded after encountering ${diagnosticErrors.length} ` +
              `error(s) / recovery event(s).`,
            suggestion:
              "Review the timeline above to understand what went wrong and how the agent recovered.",
          };
          await writeDiagnosticLog(successWithRecoveryEntry);
        }

        return { status: "completed", result: parsed.thought };
      }

      // ── Find and execute the requested tool ──────────────────────────
      const tool = this.tools.find((t) => t.name === parsed.action);
      if (!tool) {
        const stepDurationMs = Date.now() - stepStartedAt;
        cumulativeDurationMs += stepDurationMs;
        diagnosticErrors.push({
          step,
          type: "unknown_tool",
          detail: `Tool "${parsed.action}" does not exist`,
        });
        timeline.push({
          step,
          profile: stepProfile,
          action: parsed.action,
          durationMs: stepDurationMs,
          status: "unknown_tool",
          detail: `Available: ${this.tools.map((t) => t.name).join(", ")}`,
        });
        log.warn("agent_unknown_tool", {
          step,
          action: parsed.action,
          availableTools: this.tools.map((t) => t.name),
        });
        context +=
          `\nTool "${parsed.action}" does not exist. ` +
          `Available tools: ${this.tools.map((t) => t.name).join(", ")}.`;
        continue;
      }

      let result: unknown;
      try {
        const toolStartedAt = Date.now();
        result = await tool.execute(parsed.input);
        let resultSize = -1;
        try {
          resultSize = JSON.stringify(result).length;
        } catch {
          log.warn("agent_tool_result_not_serializable", {
            step,
            tool: parsed.action,
          });
        }
        const toolDurationMs = Date.now() - toolStartedAt;
        log.info("agent_tool_executed", {
          step,
          tool: parsed.action,
          durationMs: toolDurationMs,
          resultSize,
        });
      } catch (error) {
        const stepDurationMs = Date.now() - stepStartedAt;
        cumulativeDurationMs += stepDurationMs;
        toolsUsedSet.add(parsed.action);
        diagnosticErrors.push({
          step,
          type: "tool_error",
          detail: `Tool "${parsed.action}" failed: ${String(error)}`,
        });
        timeline.push({
          step,
          profile: stepProfile,
          action: parsed.action,
          durationMs: stepDurationMs,
          status: "failed",
          detail: String(error),
        });
        context += `\nTool "${parsed.action}" failed: ${String(error)}`;
        log.warn("agent_tool_failed", {
          step,
          tool: parsed.action,
          error: String(error),
        });
        emit({
          type: "tool:error",
          payload: { tool: parsed.action, error: String(error) },
        });
        continue;
      }

      emit({ type: "tool:result", payload: { tool: parsed.action, result } });
      toolsUsedSet.add(parsed.action);
      context += `\nStep ${step} — "${parsed.action}" returned: ${JSON.stringify(result)}`;
      const stepDurationMs = Date.now() - stepStartedAt;
      cumulativeDurationMs += stepDurationMs;
      timeline.push({
        step,
        profile: stepProfile,
        action: parsed.action,
        durationMs: stepDurationMs,
        status: "success",
      });
      log.info("agent_step_finished", {
        step,
        durationMs: stepDurationMs,
        contextLength: context.length,
      });
    }

    /* Loop exhausted without the model returning action "none". */
    log.warn("agent_max_steps_reached", {
      durationMs: Date.now() - runStartedAt,
      task,
    });

    /* Generate a human-readable failure summary using the fast model. */
    const maxStepsPrompt =
      `You are a debugging assistant.\n` +
      `An AI agent attempted the following task but exhausted its step limit (${MAX_STEPS} steps) ` +
      `without completing it.\n\n` +
      `Task: ${task}\n\n` +
      `Accumulated context (what was tried):\n${context.slice(-MAX_STEPS_SUMMARY_CONTEXT_WINDOW)}\n\n` +
      `Please provide:\n` +
      `1. A brief summary of what was attempted.\n` +
      `2. Where the agent appears to have gotten stuck.\n` +
      `3. Concrete suggestions for what to try differently (e.g., break the task into smaller ` +
      `steps, rephrase the task, provide more context, use a different approach).`;

    let failureSummary = "Max steps reached without a conclusive answer.";
    try {
      const summaryResult = await generateWithMetadata(maxStepsPrompt, {
        model: FAST_SUMMARY_MODEL,
      });
      failureSummary = summaryResult.response.trim();
    } catch (e) {
      log.warn("agent_max_steps_summary_failed", { error: String(e) });
    }

    /* Persist the failure in memory so future runs can learn from it. */
    await addMemory(
      `Task: ${task} → FAILED (max_steps). Summary: ${failureSummary.slice(0, 500)}`,
    );

    emit({
      type: "agent:max_steps",
      payload: { task, stepsCompleted: MAX_STEPS, summary: failureSummary },
    });

    /* Write a diagnostic log for the failure. */
    const maxStepsEntry: DiagnosticEntry = {
      timestamp: new Date().toISOString(),
      task,
      outcome: "max_steps_exhausted",
      stepsCompleted: MAX_STEPS,
      contextSnapshot: context,
      toolsUsed: [...toolsUsedSet],
      timeline,
      errors: diagnosticErrors,
      failureReason: `Agent exhausted all ${MAX_STEPS} steps without completing the task.`,
      aiCommentary: failureSummary,
      suggestion:
        "See the AI Commentary section above for specific suggestions. " +
        "Consider breaking the task into smaller sub-tasks or providing more context.",
    };
    await writeDiagnosticLog(maxStepsEntry);

    return {
      status: "max_steps",
      result: failureSummary,
      originalTask: task,
      suggestion:
        "Consider breaking the task into smaller sub-tasks or rephrasing it. " +
        "See the AI commentary for specific suggestions.",
    };
  }

  /**
   * Assemble the full prompt string sent to the LLM at each step.
   *
   * The prompt contains:
   * - A system preamble describing the agent's role.
   * - The user's task.
   * - Relevant memory entries (if any).
   * - Accumulated context from previous steps.
   * - The list of available tools with descriptions.
   * - The expected JSON response schema.
   *
   * @param task    - The user's task description.
   * @param context - Accumulated context from prior steps.
   * @param memory  - Relevant memory strings.
   * @returns The fully assembled prompt string.
   */
  private buildPrompt(
    task: string,
    context: string,
    memory: string[],
  ): string {
    const memoryBlock =
      memory.length > 0 ? `Recent memory:\n${memory.join("\n")}\n\n` : "";

    const contextBlock = context ? `Context so far:\n${context}\n\n` : "";

    const toolList = this.tools
      .map((t) => `- ${t.name}: ${t.description}`)
      .join("\n");

    return (
      `You are an AI agent with access to tools.\n\n` +
      `Task:\n${task}\n\n` +
      memoryBlock +
      contextBlock +
      `Available tools:\n${toolList}\n\n` +
      `Respond ONLY with a single valid JSON object — no markdown, no extra text:\n` +
      `{\n` +
      `  "thought": "your reasoning",\n` +
      `  "action": "tool_name or none",\n` +
      `  "input": {}\n` +
      `}\n\n` +
      `Use action "none" when the task is fully complete.`
    );
  }
}
