/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StepDefinitionOneOf
 */
export interface StepDefinitionOneOf {
    /**
     * Task text to run for this workflow step.
     * @type {string}
     * @memberof StepDefinitionOneOf
     */
    task: string;
}

/**
 * Check if a given object implements the StepDefinitionOneOf interface.
 */
export function instanceOfStepDefinitionOneOf(value: object): value is StepDefinitionOneOf {
    if (!('task' in value) || value['task'] === undefined) return false;
    return true;
}

export function StepDefinitionOneOfFromJSON(json: any): StepDefinitionOneOf {
    return StepDefinitionOneOfFromJSONTyped(json, false);
}

export function StepDefinitionOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): StepDefinitionOneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'task': json['task'],
    };
}

  export function StepDefinitionOneOfToJSON(json: any): StepDefinitionOneOf {
      return StepDefinitionOneOfToJSONTyped(json, false);
  }

  export function StepDefinitionOneOfToJSONTyped(value?: StepDefinitionOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'task': value['task'],
    };
}

