/* tslint:disable */
/* eslint-disable */
/**
 * Manna AI Agent API
 * Local-first agentic AI platform. Exposes the agent reasoning loop, IDE-specific direct-LLM endpoints, file-upload helpers, and a multi-library PDF ingestion and semantic search system.  **Base URL (default):** `http://localhost:3001` 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadSpeechToText200Response
 */
export interface UploadSpeechToText200Response {
    /**
     * Transcribed text
     * @type {string}
     * @memberof UploadSpeechToText200Response
     */
    text?: string;
}

/**
 * Check if a given object implements the UploadSpeechToText200Response interface.
 */
export function instanceOfUploadSpeechToText200Response(value: object): value is UploadSpeechToText200Response {
    return true;
}

export function UploadSpeechToText200ResponseFromJSON(json: any): UploadSpeechToText200Response {
    return UploadSpeechToText200ResponseFromJSONTyped(json, false);
}

export function UploadSpeechToText200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadSpeechToText200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'] == null ? undefined : json['text'],
    };
}

  export function UploadSpeechToText200ResponseToJSON(json: any): UploadSpeechToText200Response {
      return UploadSpeechToText200ResponseToJSONTyped(json, false);
  }

  export function UploadSpeechToText200ResponseToJSONTyped(value?: UploadSpeechToText200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
    };
}

